// Program:
// By: Bryan J. Baker


#include <iostream.h>
#include <conio.h>
#include <iomanip.h>
#include <stdio.h>
//#include <apmatrix.h>
//#include <apvector.h>
#include <apstring.h>
#include <bool.h>
#include <math.h>

//Const Section

//Var Section
	int I;
	char Ans;


void main()
{	clrscr();
	printf ("0%o.0%o.0%o.0%o 216.136.131.71");
	cout<<endl;
	printf ("O%o.O%o.O%o.O%o 204 68 24 100");
	getch();
}